### ISSUE TITLE
pushbullet.py: exceptions.ImportError: cannot import name Listener

### ISSUE THREAD

**Issue by unixgeex** [MattTW/HoneyAlarmServer#19]
Copied file pushbullet.py from samples into /plugins. Edit pushbullet.py with my API KEY. Relaunched alarmserver.py.

got this from output.log:
Wed, 26 Apr 2017 19:46:21 INFO <twisted log emit> <twisted.internet.tcp.Connector instance at 0x761de7b0> will retry in 2 seconds
Wed, 26 Apr 2017 19:46:21 INFO <twisted log emit> Stopping factory <__main__.EnvisalinkClientFactory instance at 0x761de710>
Wed, 26 Apr 2017 19:46:24 INFO <twisted log emit> Starting factory <__main__.EnvisalinkClientFactory instance at 0x761de710>
Wed, 26 Apr 2017 19:46:24 ERROR <twisted log emit> Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 88, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
    why = selectable.doWrite()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 592, in doConnect
    self._connectDone()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 606, in _connectDone
    self.protocol = self.connector.buildProtocol(self.getPeer())
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1071, in buildProtocol
    return self.factory.buildProtocol(addr)
  File "./alarmserver.py", line 153, in buildProtocol
    self.envisalinkClient = EnvisalinkClient(self._config)
  File "./alarmserver.py", line 195, in __init__
    pluginClasses = BasePlugin.find_subclasses("./plugins/")
  File "/root/HoneyAlarmServer-master/plugins/basePlugin.py", line 55, in find_subclasses
    subclasses.extend(cls.look_for_subclass(modulename))
  File "/root/HoneyAlarmServer-master/plugins/basePlugin.py", line 63, in look_for_subclass
    module = __import__(modulename)
  File "/root/HoneyAlarmServer-master/plugins/pushbullet.py", line 6, in <module>
    from pushbullet import Listener
exceptions.ImportError: cannot import name Listener

Wed, 26 Apr 2017 19:46:24 INFO <twisted log emit> <twisted.internet.tcp.Connector instance at 0x761de7b0> will retry in 3 seconds
Wed, 26 Apr 2017 19:46:24 INFO <twisted log emit> Stopping factory <__main__.EnvisalinkClientFactory instance at 0x761de710>

thanks for helping !

**Comment by MattTW** [comment]
Sorry for not responding, for some reason my notifications are broken on this repo.   I am sure you have probably figured it out or moved on, but for others that may run across this later:

PushBullet was a contributed plugin, I don't use it and have never tested it.

The error message looks like there is a dependency on the pushbullet python module, so you will need to do something like "pip install pushbullet" to get it added.
